package tw.thorsheep.studentjournal

import android.app.DatePickerDialog
import android.app.TimePickerDialog
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyListScope
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.selection.toggleable
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.math.BigDecimal
import java.time.LocalDate
import java.time.LocalTime
import java.time.YearMonth

class MainActivity : ComponentActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); enableEdgeToEdge(); setContent { AppTheme { Journal() } } } }
@Composable private fun AppTheme(content: @Composable () -> Unit)=MaterialTheme(colorScheme=lightColorScheme(primary=Color(0xFF356B58),secondary=Color(0xFF9B6C3C),background=Color(0xFFF6F8F3),surface=Color(0xFFF6F8F3),primaryContainer=Color(0xFFD8EBDC)),content=content)
private fun money(c:Long)="NT$ "+"%,.2f".format(java.util.Locale.US,c/100.0)
private val weekdays=listOf("一","二","三","四","五","六","日")
private val categories=listOf("早餐","午餐","晚餐","飲品","點心","酒類","交通","購物","娛樂","日用品","房租","醫療","社交","禮物","數位")
private data class Destination(val id:String,val title:String,val icon:androidx.compose.ui.graphics.vector.ImageVector)
private val destinations=listOf(Destination("home","首頁",Icons.Outlined.Home),Destination("money","記帳",Icons.Outlined.AccountBalanceWallet),Destination("course","課表",Icons.Outlined.DateRange),Destination("task","待辦",Icons.Outlined.CheckCircle),Destination("announcements","公告",Icons.Outlined.Campaign))
private val defaultQuick=listOf("money","course","task","announcements")

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun Journal(){
 val context=LocalContext.current;val db=remember{JournalDb.get(context)};val entries by db.entries().observe().collectAsStateWithLifecycle(emptyList());val subs by db.subscriptions().observe().collectAsStateWithLifecycle(emptyList());val ids=subs.map{it.sourceId};val news by db.announcements().observe(ids).collectAsStateWithLifecycle(emptyList());val scope=rememberCoroutineScope();val snack=remember{SnackbarHostState()};val prefs=remember{context.getSharedPreferences("settings",0)}
 var page by rememberSaveable{mutableStateOf("home")};var drawerOpen by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<Entry?>(null)};var remove by remember{mutableStateOf<Entry?>(null)};var restore by remember{mutableStateOf<List<Entry>?>(null)};var day by rememberSaveable{mutableIntStateOf(LocalDate.now().dayOfWeek.value)};var month by rememberSaveable{mutableStateOf(YearMonth.now().toString())};var busy by remember{mutableStateOf(false)};var quick by remember{mutableStateOf(prefs.getString("quick",defaultQuick.joinToString(","))!!.split(",").filter{it.isNotBlank()}.take(4))}
 fun toast(text:String){scope.launch{snack.showSnackbar(text)}}; fun create(type:String){edit=Entry(type=type,title="",date=if(type=="money")LocalDate.now().toString()else"",day=day,start="09:00",end="10:00")}
 val export=rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/json")){uri->if(uri!=null)scope.launch{busy=true;try{withContext(Dispatchers.IO){context.contentResolver.openOutputStream(uri)?.bufferedWriter()?.use{it.write(Backup.encode(entries))}};toast("備份已匯出")}catch(e:Exception){toast("匯出失敗：${e.message}")}finally{busy=false}}}
 val import=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null)scope.launch{busy=true;try{restore=withContext(Dispatchers.IO){context.contentResolver.openInputStream(uri)?.bufferedReader()?.use{Backup.decode(it.readText())}?:error("無法讀取檔案")}}catch(e:Exception){toast("匯入失敗：${e.message}")}finally{busy=false}}}
 val drawerState=rememberDrawerState(if(drawerOpen)DrawerValue.Open else DrawerValue.Closed)
 LaunchedEffect(drawerOpen){if(drawerOpen)drawerState.open() else drawerState.close()}
 ModalNavigationDrawer(drawerState=drawerState,gesturesEnabled=false,drawerContent={ModalDrawerSheet{Spacer(Modifier.height(16.dp));Text("Simple App",Modifier.padding(24.dp,8.dp),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);destinations.forEach{d->NavigationDrawerItem(label={Text(d.title)},selected=page==d.id,onClick={page=d.id;drawerOpen=false},icon={Icon(d.icon,null)},modifier=Modifier.padding(NavigationDrawerItemDefaults.ItemPadding))};HorizontalDivider(Modifier.padding(vertical=8.dp));NavigationDrawerItem(label={Text("設定")},selected=page=="settings",onClick={page="settings";drawerOpen=false},icon={Icon(Icons.Outlined.Settings,null)},modifier=Modifier.padding(NavigationDrawerItemDefaults.ItemPadding));NavigationDrawerItem(label={Text("帳戶（即將推出）")},selected=false,onClick={toast("帳戶功能會在後續版本推出")},icon={Icon(Icons.Outlined.Person,null)},modifier=Modifier.padding(NavigationDrawerItemDefaults.ItemPadding))}}){
  Scaffold(snackbarHost={SnackbarHost(snack)},topBar={TopAppBar(title={Text(destinations.find{it.id==page}?.title?:"設定")},navigationIcon={IconButton(onClick={drawerOpen=true}){Icon(Icons.Outlined.Menu,"開啟側欄")}})},bottomBar={if(page!="settings")BottomBar(page,quick,{page="home"},{page=it})},floatingActionButton={if(page in listOf("money","course","task"))FloatingActionButton(onClick={create(page)}){Icon(Icons.Outlined.Add,"新增")}}){pad->
   Box(Modifier.padding(pad)){if(busy)LinearProgressIndicator(Modifier.fillMaxWidth());when(page){"home"->Home(entries,news,{page="announcements"});"money"->Money(entries,month,{month=it},{edit=it},{remove=it});"course"->Courses(entries,day,{day=it},{edit=it},{remove=it});"task"->Tasks(entries,{edit=it},{remove=it}){e,v->scope.launch{db.entries().save(e.copy(done=v))}};"announcements"->Announcements(news,ids,{id,on->scope.launch{if(on)db.subscriptions().save(Subscription(id))else db.subscriptions().delete(id)}},{source->scope.launch{busy=true;try{val rows=withContext(Dispatchers.IO){AnnouncementFetcher.fetch(source)};db.announcements().insertAll(rows);db.announcements().trim(System.currentTimeMillis()-120L*24*60*60*1000);toast("${source.name}：已更新 ${rows.size} 筆")}catch(e:Exception){toast("${source.name} 更新失敗：${e.message}")}finally{busy=false}}},{a->scope.launch{db.announcements().markRead(a.id)};context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(a.url)))});else->Settings(quick,{q->quick=q;prefs.edit().putString("quick",q.joinToString(",")).apply()},{export.launch("simple-app-${LocalDate.now()}.json")},{import.launch(arrayOf("application/json","text/plain"))})}}
  }
 }
 edit?.let{old->Editor(old,entries.filter{it.type=="course"},{edit=null}){row->scope.launch{try{db.entries().save(row);edit=null;toast("已儲存")}catch(e:Exception){toast("儲存失敗：${e.message}")}}}}
 remove?.let{row->AlertDialog({remove=null},title={Text("刪除「${row.title}」？")},text={Text("刪除後無法復原。")},confirmButton={TextButton({scope.launch{db.entries().delete(row);remove=null}}){Text("刪除")}},dismissButton={TextButton({remove=null}){Text("取消")}})}
 restore?.let{rows->AlertDialog({restore=null},title={Text("確認還原備份")},text={Text("還原會完整取代目前資料。")},confirmButton={TextButton({scope.launch{db.entries().replace(rows);restore=null;toast("資料已還原")}}){Text("取代並還原")}},dismissButton={TextButton({restore=null}){Text("取消")}})}
}
@Composable private fun BottomBar(page:String,quick:List<String>,home:()->Unit,go:(String)->Unit)=NavigationBar{quick.take(2).forEach{id->destinations.find{it.id==id}?.let{d->NavigationBarItem(page==d.id,{go(d.id)},{Icon(d.icon,d.title)},label={Text(d.title)})}};NavigationBarItem(page=="home",home,{Icon(Icons.Outlined.Home,"首頁")},label={Text("首頁")});quick.drop(2).forEach{id->destinations.find{it.id==id}?.let{d->NavigationBarItem(page==d.id,{go(d.id)},{Icon(d.icon,d.title)},label={Text(d.title)})}}}
@Composable private fun ListScreen(content:LazyListScope.()->Unit)=LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp,12.dp,20.dp,96.dp),verticalArrangement=Arrangement.spacedBy(12.dp),content=content)
@Composable private fun Home(rows:List<Entry>,news:List<Announcement>,open:()->Unit)=ListScreen{val today=LocalDate.now();val monthly=rows.filter{it.type=="money"&&it.date.startsWith(YearMonth.now().toString())};item{Text("${today.monthValue} 月 ${today.dayOfMonth} 日 · 星期${weekdays[today.dayOfWeek.value-1]}",style=MaterialTheme.typography.titleLarge)};item{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.primaryContainer)){Column(Modifier.padding(20.dp)){Text("本月生活收支");Text(money(monthly.sumOf{if(it.direction=="收入")it.cents else-it.cents}),style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Bold)}}};item{Heading("今日課程")};val courses=rows.filter{it.type=="course"&&it.day==today.dayOfWeek.value}.sortedBy{it.start};if(courses.isEmpty())item{Empty("今天沒有課程","到課表加入你的第一堂課。")}else items(courses.take(4)){EntryCard(it,rows,{},{})};item{Heading("校園公告")};if(news.isEmpty())item{Empty("尚無訂閱公告","到公告頁選擇學校與單位。")}else items(news.take(3)){a->Text("${a.title}\n${a.date}",Modifier.fillMaxWidth().clickable{open()}.padding(vertical=8.dp))}}
@Composable private fun Money(rows:List<Entry>,month:String,setMonth:(String)->Unit,edit:(Entry)->Unit,delete:(Entry)->Unit)=ListScreen{item{Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween,Alignment.CenterVertically){TextButton({setMonth(YearMonth.parse(month).minusMonths(1).toString())}){Text("上個月")};Text(month,style=MaterialTheme.typography.titleLarge);TextButton({setMonth(YearMonth.parse(month).plusMonths(1).toString())}){Text("下個月")}}};val list=rows.filter{it.type=="money"&&it.date.startsWith(month)}.sortedByDescending{it.date};item{Text("收入 ${money(list.filter{it.direction=="收入"}.sumOf{it.cents})}　支出 ${money(list.filter{it.direction=="支出"}.sumOf{it.cents})}")};if(list.isEmpty())item{Empty("這個月還沒有紀錄","點右下角 ＋ 記下第一筆收支。")}else items(list){EntryCard(it,rows,{edit(it)},{delete(it)})}}
@Composable private fun Courses(rows:List<Entry>,day:Int,setDay:(Int)->Unit,edit:(Entry)->Unit,delete:(Entry)->Unit)=ListScreen{item{Heading("每週課表")};item{Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween){weekdays.forEachIndexed{i,t->FilterChip(day==i+1,{setDay(i+1)},label={Text(t)})}}};val list=rows.filter{it.type=="course"&&it.day==day}.sortedBy{it.start};if(list.isEmpty())item{Empty("星期${weekdays[day-1]}沒有課程","點右下角 ＋ 新增課程。")}else items(list){EntryCard(it,rows,{edit(it)},{delete(it)})}}
@Composable private fun Tasks(rows:List<Entry>,edit:(Entry)->Unit,delete:(Entry)->Unit,check:(Entry,Boolean)->Unit)=ListScreen{item{Heading("我的待辦")};val list=rows.filter{it.type=="task"}.sortedWith(compareBy<Entry>{it.done}.thenBy{it.date.ifEmpty{"9999"}});if(list.isEmpty())item{Empty("留一個位置給下一件事","新增作業、考試或生活待辦。")}else items(list){e->EntryCard(e,rows,{edit(e)},{delete(e)}){check(e,it)}}}
@Composable private fun Announcements(rows:List<Announcement>,subscribed:List<String>,toggle:(String,Boolean)->Unit,refresh:(AnnouncementSource)->Unit,open:(Announcement)->Unit)=ListScreen{item{Heading("校園公告")};item{Text("只提供已驗證的中大與海大公開公告來源。選擇單位後按更新，閱讀全文時才開啟校方網站。")};AnnouncementCatalog.sources.groupBy{it.school}.forEach{(school,schoolSources)->item{Text(school,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};schoolSources.groupBy{it.group}.forEach{(group,sources)->item{Text(group,style=MaterialTheme.typography.labelLarge)};items(sources){s->Row(Modifier.fillMaxWidth().toggleable(s.id in subscribed){toggle(s.id,it)}.padding(vertical=4.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(s.id in subscribed,{toggle(s.id,it)});Text(s.name,Modifier.weight(1f));TextButton({refresh(s)}){Text("更新")}}}}};item{Heading("已接收公告")};if(rows.isEmpty())item{Empty("尚無公告","訂閱單位後，按右側「更新」。")}else items(rows){a->Card(Modifier.fillMaxWidth().clickable{open(a)}){Column(Modifier.padding(14.dp)){Text(AnnouncementCatalog.sources.find{it.id==a.sourceId}?.name?:"公告",style=MaterialTheme.typography.labelMedium);Text(a.title,fontWeight=FontWeight.SemiBold);if(a.date.isNotBlank())Text(a.date,style=MaterialTheme.typography.bodySmall)}}}}
@Composable private fun Settings(quick:List<String>,save:(List<String>)->Unit,export:()->Unit,import:()->Unit)=ListScreen{item{Heading("底部常用功能")};item{Text("首頁固定在正中間；最多選四項。未設定時為記帳、課表、待辦、公告。")};items(destinations.filter{it.id!="home"}){d->val checked=d.id in quick;Row(Modifier.fillMaxWidth().toggleable(checked){if(it&&quick.size<4)save(quick+d.id)else if(!it)save(quick-d.id)}.padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(checked,null);Text(d.title)}};item{Heading("資料備份")};item{Button(export,Modifier.fillMaxWidth()){Text("匯出全部資料")};OutlinedButton(import,Modifier.fillMaxWidth()){Text("選擇備份檔還原")};Text("帳戶按鈕已預留，尚未啟用。\n\nSimple App 2.0.0")}}
@Composable private fun Heading(text:String)=Text(text,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)
@Composable private fun Empty(title:String,detail:String)=Column(Modifier.padding(vertical=20.dp)){Text(title,style=MaterialTheme.typography.titleMedium);Text(detail,color=MaterialTheme.colorScheme.onSurfaceVariant)}
@Composable private fun EntryCard(e:Entry,all:List<Entry>,edit:()->Unit,delete:()->Unit,check:((Boolean)->Unit)?=null)=Card(Modifier.fillMaxWidth().clickable(onClick=edit),shape=RoundedCornerShape(18.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){if(check!=null)Checkbox(e.done,check);Column(Modifier.weight(1f)){Text(e.title,fontWeight=FontWeight.SemiBold);when(e.type){"money"->Text("${e.direction} · ${e.category.ifBlank{"未分類"}} · ${e.date} · ${money(e.cents)}");"course"->Text("${e.start}–${e.end} · ${e.room.ifEmpty{"未填教室"}}");else->{Text(if(e.done)"已完成"else e.date.ifEmpty{"無截止日期"});all.find{it.id==e.courseId}?.let{Text("課程：${it.title}",style=MaterialTheme.typography.bodySmall)}}}};IconButton(delete){Icon(Icons.Outlined.Delete,"刪除")}}}
@Composable private fun Editor(old:Entry,courses:List<Entry>,dismiss:()->Unit,save:(Entry)->Unit){var title by rememberSaveable(old.id){mutableStateOf(old.title)};var date by rememberSaveable(old.id){mutableStateOf(old.date)};var amount by rememberSaveable(old.id){mutableStateOf(if(old.cents>0)BigDecimal.valueOf(old.cents,2).toPlainString()else"")};var direction by rememberSaveable(old.id){mutableStateOf(old.direction)};var category by rememberSaveable(old.id){mutableStateOf(old.category)};var note by rememberSaveable(old.id){mutableStateOf(old.note)};var day by rememberSaveable(old.id){mutableIntStateOf(old.day)};var start by rememberSaveable(old.id){mutableStateOf(old.start)};var end by rememberSaveable(old.id){mutableStateOf(old.end)};var room by rememberSaveable(old.id){mutableStateOf(old.room)};var teacher by rememberSaveable(old.id){mutableStateOf(old.teacher)};var courseId by rememberSaveable(old.id){mutableStateOf(old.courseId)};var err by remember{mutableStateOf("")};AlertDialog(dismiss,title={Text(if(old.title.isEmpty())"新增"else"編輯")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){when(old.type){"money"->{Row{listOf("支出","收入").forEach{FilterChip(direction==it,{direction=it},label={Text(it)},modifier=Modifier.padding(end=4.dp))}};CategoryPicker(category){category=it};OutlinedTextField(amount,{amount=it},label={Text("金額（新台幣）")});DateButton(date.ifBlank{LocalDate.now().toString()}){date=it};OutlinedTextField(note,{note=it},label={Text("備註（選填）")})};"course"->{OutlinedTextField(title,{title=it},label={Text("課程名稱")});Row{weekdays.forEachIndexed{i,t->FilterChip(day==i+1,{day=i+1},label={Text(t)},modifier=Modifier.padding(end=2.dp))}};TimeButton("開始時間",start){start=it};TimeButton("結束時間",end){end=it};OutlinedTextField(room,{room=it},label={Text("教室（選填）")});OutlinedTextField(teacher,{teacher=it},label={Text("教師（選填）")})};else->{OutlinedTextField(title,{title=it},label={Text("待辦名稱")});DateButton(date.ifBlank{LocalDate.now().toString()},"截止日期"){date=it};OutlinedTextField(note,{note=it},label={Text("備註（選填）")})}};if(err.isNotBlank())Text(err,color=MaterialTheme.colorScheme.error)}},confirmButton={TextButton({try{val e=old.copy(title=if(old.type=="money")category else title.trim(),date=date,cents=if(old.type=="money")amount.toBigDecimal().movePointRight(2).longValueExact()else 0,direction=direction,category=category,note=note,day=day,start=start,end=end,room=room,teacher=teacher,courseId=courseId);Backup.validate(e);save(e)}catch(e:Exception){err=e.message?:"請檢查輸入"}}){Text("儲存")}},dismissButton={TextButton(dismiss){Text("取消")}})}
@Composable private fun CategoryPicker(value:String,set:(String)->Unit){var open by remember{mutableStateOf(false)};Box{OutlinedButton({open=true}){Text(value.ifBlank{"選擇分類"})};DropdownMenu(open,{open=false}){categories.forEach{c->DropdownMenuItem({Text(c)},{set(c);open=false})}}}}
@Composable private fun DateButton(value:String,label:String="日期",set:(String)->Unit){val ctx=LocalContext.current;OutlinedButton({val d=runCatching{LocalDate.parse(value)}.getOrElse{LocalDate.now()};DatePickerDialog(ctx,{_,y,m,day->set("%04d-%02d-%02d".format(y,m+1,day))},d.year,d.monthValue-1,d.dayOfMonth).show()}){Text("$label：$value")}}
@Composable private fun TimeButton(label:String,value:String,set:(String)->Unit){val ctx=LocalContext.current;OutlinedButton({val t=runCatching{LocalTime.parse(value)}.getOrElse{LocalTime.of(9,0)};TimePickerDialog(ctx,{_,h,m->set("%02d:%02d".format(h,m))},t.hour,t.minute,true).show()}){Text("$label：$value")}}
